In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [49]:
def read_pi(filename:str) -> np.array:
    with open(filename) as f:
        lines = f.readlines()
    feats = []

    for line in lines[1: int(lines[0])+1]:
        feats.append( int(int(line.split(' ')[-1].strip())))
    
    return np.array(feats)

In [32]:
def normalize_data(data:np.array) -> np.array:
    return data / np.abs(data).max()

In [18]:
line = '1 0 5 2 0 15 100 9 200 30 300 6 400'
items = np.array(line.split(' '))
cands = [int(items[3 + i * 2])-1 for i in range(5)]
print(cands)

[1, 14, 8, 29, 5]


In [55]:
instance = 'vn_30'
filename = f'result/{instance}/pi/'

pi = read_pi(filename=filename + '0.txt')
norm_pi = normalize_data(pi)
#print(norm_pi)
norm_pi = normalize_data(pi)
color = np.array([ 'darkblue' for i in range(norm_pi.size)])
color[np.argwhere(norm_pi < 0)] = 'red'

print(color)


['darkblue' 'red' 'darkblue' 'darkblue' 'darkblue' 'darkblue' 'darkblue'
 'darkblue' 'darkblue' 'red' 'darkblue' 'darkblue' 'darkblue' 'darkblue'
 'darkblue' 'darkblue' 'darkblue' 'darkblue' 'darkblue' 'darkblue' 'red'
 'darkblue' 'darkblue' 'red' 'darkblue' 'darkblue' 'darkblue' 'darkblue'
 'darkblue' 'darkblue']


In [18]:
line = "25 30874 500 19 108227 380 17 170177 342 14 192679 284 27 212061 543 24 217904 485 22 243059 445 28 248115 562 3 288879 66 5 290081 105 26 292309 522 9 383580 188 11 408771 231 13 456957 267 12 501432 251 10 541397 219 21 555265 435 18 570107 378 1 597818 32 16 614892 338"
items = line.strip().split(' ')

batch_size = 10
n_nodes = 30

edge_index = []
for batch in range(batch_size):
    for item in range(len(items)//3):
        edge_index.append( int( items[item * 3]) + batch)

edge_index = np.array(edge_index).reshape(1, -1, 20)
print(edge_index)
print(edge_index.shape)
new_edge_index = edge_index.reshape(batch_size, -1, 20)
print(np.arange(batch_size).reshape(-1, 1, 1), np.arange(n_nodes).reshape(1, -1, 1))

exit
#print(new_edge_index)


[[[25 19 17 14 27 24 22 28  3  5 26  9 11 13 12 10 21 18  1 16]
  [26 20 18 15 28 25 23 29  4  6 27 10 12 14 13 11 22 19  2 17]
  [27 21 19 16 29 26 24 30  5  7 28 11 13 15 14 12 23 20  3 18]
  [28 22 20 17 30 27 25 31  6  8 29 12 14 16 15 13 24 21  4 19]
  [29 23 21 18 31 28 26 32  7  9 30 13 15 17 16 14 25 22  5 20]
  [30 24 22 19 32 29 27 33  8 10 31 14 16 18 17 15 26 23  6 21]
  [31 25 23 20 33 30 28 34  9 11 32 15 17 19 18 16 27 24  7 22]
  [32 26 24 21 34 31 29 35 10 12 33 16 18 20 19 17 28 25  8 23]
  [33 27 25 22 35 32 30 36 11 13 34 17 19 21 20 18 29 26  9 24]
  [34 28 26 23 36 33 31 37 12 14 35 18 20 22 21 19 30 27 10 25]]]
(1, 10, 20)
[[[0]]

 [[1]]

 [[2]]

 [[3]]

 [[4]]

 [[5]]

 [[6]]

 [[7]]

 [[8]]

 [[9]]]
[[[25 19 17 14 27 24 22 28  3  5 26  9 11 13 12 10 21 18  1 16]]

 [[26 20 18 15 28 25 23 29  4  6 27 10 12 14 13 11 22 19  2 17]]

 [[27 21 19 16 29 26 24 30  5  7 28 11 13 15 14 12 23 20  3 18]]

 [[28 22 20 17 30 27 25 31  6  8 29 12 14 16 15 13 24 21  4 19]]

 [

In [11]:
batch_size = 10
n_nodes = 30
n_neighbours = 20

edges = np.arange(n_nodes * n_neighbours).reshape(1, n_nodes, n_neighbours)
print(edges.shape)
np.concatenate(edges).shape


(1, 30, 20)


(30, 20)